site_name: Case DataSUS
site_author: Rodrigo Barreiro
site_url: https://barreiro-r.github.io/case-datasus
repo_url: https://github.com/barreiro-r/case-datasus
repo_name: barreiro-r/case-datasus



markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette: 
    primary: black
    accent: deep_purple
  font:
    text: Ubuntu
    code: Ubuntu Mono
  language: en
  logo: assets/images/logo-datasus.png
  icon:
    repo: fontawesome/brands/git-alt  
  features:
    - navigation.sections

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/barreiro-r/case-datasus
      
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rodrigoasbarreiro
      name: in/rodrigoasbarreiro

plugins:
  - social


nav:
  - index.md 
  - About DataSUS: about-datasus.md
  - ETL process: etl-process.md
  - Dashboards:
    - APAQ-AQ: dashboard-apac-aq.md
    - APAQ-AM: dashboard-apac-am.md
  - Analysis:
    - HER-2: analysis-her2.md
    - Antipsychotics: analysis-antipsychotics.md
    - Immunotherapy: analysis-immunotherapy.md
  - Additional info:
    - Supplementary Tables: sup-tables.md
    - Limitations and Considerations: limitations-considerations.md
    - Git Project Organization: project-organization.md
      
